version: '3'
services:
  flask_app:
    build:
      context: ./app/flask_app
      dockerfile: Dockerfile_flask
    ports:
      - '8080:5000'
    environment:
      - DOCKER_ENV=true
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8000'